import { Category } from '@/types/constants';

export const categoryIcons: Record<Category, string> = {
    [Category.FRUITS]: '🍎',
    [Category.VEGETABLES]: '🥕',
    [Category.MEAT]: '🥩',
    [Category.FISH]: '🐟',
    [Category.POULTRY]: '🍗',
    [Category.EGGS]: '🥚',
    [Category.DAIRY]: '🥛',
    [Category.CHEESE]: '🧀',
    [Category.GRAINS]: '🍞',
    [Category.CANNED]: '🥫',
    [Category.SPICES]: '🧂',
    [Category.OILS]: '🫒',
    [Category.BAKING]: '🥧',
    [Category.SNACKS]: '🍿',
    [Category.BEVERAGES]: '🥤',
    [Category.ALCOHOL]: '🍺',
    [Category.CLEANING]: '🧹',
    [Category.PERSONAL_CARE]: '🧴',
    [Category.BABY_CARE]: '👶',
    [Category.PET_SUPPLIES]: '🐕',
};

export const categoryColors: Record<Category, string> = {
    [Category.FRUITS]: '#FF6B6B',
    [Category.VEGETABLES]: '#51CF66',
    [Category.MEAT]: '#C92A2A',
    [Category.FISH]: '#339AF0',
    [Category.POULTRY]: '#FFA94D',
    [Category.EGGS]: '#FFE066',
    [Category.DAIRY]: '#74C0FC',
    [Category.CHEESE]: '#FFD43B',
    [Category.GRAINS]: '#D0BFFF',
    [Category.CANNED]: '#868E96',
    [Category.SPICES]: '#FD7E14',
    [Category.OILS]: '#8CE99A',
    [Category.BAKING]: '#FF8CC8',
    [Category.SNACKS]: '#A855F7',
    [Category.BEVERAGES]: '#3B82F6',
    [Category.ALCOHOL]: '#DC2626',
    [Category.CLEANING]: '#10B981',
    [Category.PERSONAL_CARE]: '#EC4899',
    [Category.BABY_CARE]: '#F472B6',
    [Category.PET_SUPPLIES]: '#92400E',
};
